import Image from 'next/image';
import Head from './styled';

const HeadPage = () => {
  return (
    <Head>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      <link rel="icon" href="/favicon.ico" />
      <section className="service">
        <div className="img-dotted">
          <Image
            id="image-dotted"
            src={'/Images/image4.png'}
            width={70}
            height={100}
            alt="No photo"
          />
        </div>
        <div className="info">
          <h2 id="service-info">Virtual healthcare for you</h2>
          <p id="text">
            Trafalgar provides progressive, and affordable healthcare, accessible on mobile and
            online for everyone
          </p>
          <button className="btn">Consult today</button>
        </div>
        <div className="img">
          <Image id="image" src="/Images/image1.png" width={522} height={447} alt="No photo" />
        </div>
      </section>
    </Head>
  );
};

export default HeadPage;
