import type { NextPage } from 'next';
import Head from 'next/head';
import Menu from '../src/components/Navbar';
import Log from '../src/components/Logo';
import Header from '../src/components/Header';
import OurServices from '../src/components/Services';
import FooterPage from '../src/components/Footer';
import LeadingPage from '../src/components/Leading';
import DownloadPage from '../src/components/Download';
import Reviews from '../src/components/Testimonials';
import TitleArticle from '../src/components/ArticleTitle';
import BasicButtons from '../src/components/ViewallButton';
import { Articles } from '../src/components/Articles';
import { Box } from '@mui/material';

const Home: NextPage = () => {
  return (
    <section className="id-main">
      <Menu />
      <Log />
      <Header />
      <Head>
        <title>Trafalgar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Mulish:wght@200;300;400;500;600;700;900&family=Roboto:wght@100;300;400;500;700&display=swap"
          rel="stylesheet"></link>
      </Head>
      <OurServices />
      <LeadingPage />
      <DownloadPage />
      <TitleArticle />
      <Box sx={{ display: 'flex' }}>
        <Articles
          width="250"
          height="200"
          src="/Images/laboratory.png"
          alt="no-photo"
          title="Disease detection, check 
        up in the laboratory"
          description="  Infectious diseases are caused by pathogenic microorganisms and can spread from
        person to person. They include zoonotic diseases, which are infectious diseases in
        animals that can cause illness when transmitted to humans. Over the course of
        TEPHINET history we have supported disease-specific projects that reflect global
        health priorities in a given year. Recently, our work has included support for
        eliminating hepatitis, ending polio transmission, strengthening surveillance for
        Zika and influenza, and controlling healthcare-associated infections (HAI) and
        antimicrobial resistance (AMR). Our work in these areas includes providing technical
        and logistical support for trainings, hiring and supervising research field teams,
        and administering disease-specific mini-grants to FETP trainees and graduates (for
          example, to conduct Zika detection and control activities)."
        />
        <Articles
          width="250"
          height="200"
          src="/Images/herbal.png"
          alt="no-photo"
          title="Herbal medicines that are 
        safe for consumption"
          description="Products made from botanicals, or plants, that are used to treat diseases or to maintain health are called herbal products, botanical products, or phytomedicines. A product made from plants and used solely for internal use is called an herbal supplement. Many prescription drugs and over-the-counter medicines are also made from plant products, but these products contain only purified ingredients and are regulated by the FDA. Herbal supplements may contain entire plants or plant parts."
        />
        <Articles
          width="250"
          height="200"
          src="/Images/skin.png"
          alt="no-photo"
          title="Natural care for healthy facial skin"
          description="Clean beauty is on the rise. You can see it on social media, where influencers tout that going all-natural has helped their skin look better than ever. You can see it on store shelves, where countless products market themselves alongside pictures of beautiful plants and use lingo like “nontoxic.” And many of us are taking interest: Up to 50 percent of women seek out all-natural or organic ingredients in facial skin-care products and buy those that are free of chemicals like phthalates and sulfates, according to a 2017 survey from the NPD Group."
        />
      </Box>
      <BasicButtons />
      <Reviews />
      <FooterPage />
    </section>
  );
};

export default Home;
